Range Filter Scatter Plot
TASBE/TASBEFlowAnalytics pull request #533
Opened 2022-07-28 16:58 UTC by hgscott

This code generates a gating scatter plot comparable to the Automatic Gate plots, with a red rectangle highlighting the region selected by the range filter.

This required the blankfile to be passed to the Range Filter constructor as well as the filter information.

The plot is saved in the specified plot folder with the file name RangeFilter-{channel name}-vs-{channal name}.

This does not return the handle of the scatter plot for further customization- that will be submitted in the next pull request.

Example use:
```
blankfile = DataFile('fcs', 'L-1A.fcs');
filter = {'FSC-A', [3.5 4.5], 'SSC-A', [0.75 2.5]};
RF = RangeFilter(blankfile, filter{1}, 10.^filter{2}, filter{3}, 10.^filter{4});
```
Will generate the following plot:
![RangeFilter-FSC-A-vs-SSC-A](https://user-images.githubusercontent.com/40765908/181595047-b1823efb-abf8-47dd-bf5a-4c10e9f42b69.png)

2022-07-28 18:12 UTC, jakebeal requested changes

2022-07-28 18:12 UTC, jakebeal commented on code/@RangeFilter/RangeFilter.m
> +% Specified as a sequence of blankfile,'ChannelA',[minA maxA],'ChannelB',[minB maxB]
There are cases that use the RangeFilter without a file. It would be good to support them still.

Can we make it so that the blank file is signaled by an argument pair, just like the channels are?
That would be similar to how properties are added to a call to the "legend" function, where you can give the location as the first pair of arguments.
For example one might call: "RangeFilter('PlotFile',blankfile,'ChannelA,[minA ...)" but also have it be legitimate to call: "RangeFilter('ChannelA,[minA ...)" and get no plots.

2022-07-28 18:12 UTC, jakebeal commented on code/@RangeFilter/RangeFilter.m
> +gate_fraction = TASBEConfig.get('gating.fraction');
All of this can be moved inside of the "if makeplots", since it's only needed there.

2022-07-29 18:58 UTC, hgscott commented on code/@RangeFilter/RangeFilter.m
> +gate_fraction = TASBEConfig.get('gating.fraction');
Good idea- in 43ca2bd I moved everything other than getting the makeplots value into the if statement

2022-07-29 19:18 UTC, hgscott commented on code/@RangeFilter/RangeFilter.m
> +% Specified as a sequence of blankfile,'ChannelA',[minA maxA],'ChannelB',[minB maxB]
I made the change to use argument pairs in 1cb4b16, and if makeplots is true without the file, it throws a warning.

2022-07-29 19:20 UTC, hgscott reviewed
Made requested changes- ready for re-review

2022-07-29 20:54 UTC, jakebeal approved these changes
I am approving conditional on the tests completing without error.
I also suggest improving the documentation as noted.

2022-07-29 20:54 UTC, jakebeal commented on code/@RangeFilter/RangeFilter.m
> +% Specified as a sequence of blankfile,'ChannelA',[minA maxA],'ChannelB',[minB maxB]
I don't see that reflected in the documentation here --- it would be good to add that before you merge.

2022-07-29 23:55 UTC, merged